import numpy as np
import re
import sys

_re_freq = re.compile(r"-?[0-9]*\.[0-9]")


def read_anharm_matrix(filename):
    """
    This function takes a gaussian log file with anharmonic analysis
    filename: example.log
    this function return a lower triangular matrix numpy.array
    return anharm_matrix: numpy.array (in cm-1)
    """
    with open(filename) as f:
        found_anharm_matrix = False
        append_bool = False
        anharm_matrix_list = []
        lines = f.readlines()
        for line in lines:
            if "Total Anharmonic X Matrix" in line:
                found_anharm_matrix = True
                append_bool = True
            if found_anharm_matrix == True:
                if "============================================" in line:
                    append_bool = False
                    break

            if append_bool == True:
                line = re.sub(r"D", "E", line)
                anharm_matrix_list.append(line)

    anharm_matrix_list = anharm_matrix_list[2:]
    anharm_matrix_ll = []
    for line in anharm_matrix_list:
        line_split = line.split()
        if line_split != []:
            anharm_matrix_ll.append(line_split)

    anharm_matrix_ll_array = []
    index_line_n_list = []
    max_index = 0
    for n, line in enumerate(anharm_matrix_ll):
        new_line = []
        all_digit = True
        for item in line:
            if item.isdigit():
                new_line.append(int(item))
            else:
                new_line.append(float(item))
                all_digit = False
        if all_digit:
            index_line_n_list.append(n)
            max_index = new_line[-1]

        anharm_matrix_ll_array.append(new_line)

    anharm_matrix = np.zeros((max_index, max_index))

    for n, index_line_n in enumerate(index_line_n_list):
        if n != len(index_line_n_list) - 1:
            next_index_line_n = index_line_n_list[n + 1]
            for line in anharm_matrix_ll_array[index_line_n + 1 : next_index_line_n]:
                i = line[0]
                for _j, item in enumerate(line[1:]):
                    j = anharm_matrix_ll_array[index_line_n][_j]
                    anharm_matrix[i - 1, j - 1] = item
                    # symmetrize anharmonic matrix, modify upper triangular matrix
                    anharm_matrix[j - 1, i - 1] = item
        else:
            for line in anharm_matrix_ll_array[index_line_n + 1 :]:
                i = line[0]
                for _j, item in enumerate(line[1:]):
                    j = anharm_matrix_ll_array[index_line_n][_j]
                    anharm_matrix[i - 1, j - 1] = item
                    # symmetrize anharmonic matrix, modify upper triangular matrix
                    anharm_matrix[j - 1, i - 1] = item

    return anharm_matrix


def format_anharm_matrix(anharm_matrix):
    """
    This function takes a symmetric matrix generated by "read_anharm_matrix"
    anharm_matrix: numpy.array
    return lower triangular matrix list like formated output like (in cm-1):
    1.11111E+1
    1.11111E+1 1.11111E+1
    1.11111E+1 1.11111E+1 1.11111E+1
    """
    _anharm_matrix = np.tril(anharm_matrix)
    format_output = []
    for a in _anharm_matrix:
        format_line = a[a != 0]
        format_line = list(format_line)
        format_output.append(" ".join([f"{i:.5E}" for i in format_line]))
    return format_output


def read_harm_freq(filename):
    """
    This function reads a gaussian log file with anharmonic analysis
    return harmonic frequencies (cm-1)
    """
    with open(filename) as f:
        found_harm_freq = False
        append_bool = False
        harm_freq_list = []
        lines = f.readlines()
        for line in lines:
            if "Fundamental Bands" in line:
                found_harm_freq = True
                append_bool = True
            if found_harm_freq == True:
                if "Overtones" in line:
                    append_bool = False
                    break

            if append_bool == True:
                harm_freq_list.append(line)

    harm_freq_list_clean = []
    for line in harm_freq_list[3:-1]:
        line_split = line.split()
        i = line_split.index("active") + 1

        # in some cases there will be "3722.837**********"
        if "*" in line_split[i]:
            _clean_freq_list = re.findall(_re_freq, line_split[i])
            if _clean_freq_list != []:
                _clean_freq = _clean_freq_list[0]
                line_split[i] = _clean_freq
            else:
                print("Frequency parser failed!")
                print(line_split[i])

        harm_freq_list_clean.append(float(line_split[i]))

    return harm_freq_list_clean


def read_harm_freq_another(filename):
    with open(filename) as f:
        found_harm_freq = False
        append_bool = False
        harm_freq_list = []
        lines = f.readlines()
        for line in lines:
            if "Harmonic frequencies" in line:
                found_harm_freq = True
                append_bool = True
            if found_harm_freq == True:
                if "-------------------" in line:
                    append_bool = False
                    break

            if append_bool == True:
                harm_freq_list.append(line)

    harm_freq_list_clean = []
    for line in harm_freq_list[3:-1]:
        if "Frequencies" in line:
            _freq_list = re.findall(_re_freq, line)
            if _freq_list != []:
                for _freq in _freq_list:
                    harm_freq_list_clean.append(float(_freq))

    return harm_freq_list_clean


def read_method(filename):
    with open(filename) as f:
        lines = f.readlines()
    i_list = []
    j_list = []
    for n, line in enumerate(lines):
        if "1\\1\\" in line:
            i_list.append(n)
        if "@" in line:
            j_list.append(n)

    result_sum = []
    for i, j in zip(i_list, j_list):
        sub_lines = []
        for line in lines[i : j + 1]:
            line = re.sub(r"\n", "", line)
            line = re.sub(r"\ ", "", line)
            sub_lines.append(line)
        result_sum.append("".join(sub_lines))

    # ts_bool = False
    for result_i in result_sum:
        result_list = result_i.split("\\")
        result_list_lower = [item.lower() for item in result_list]
        if "freq" in result_list_lower:
            i = result_list_lower.index("freq")
            method = result_list[i + 1]
            basissets = result_list[i + 2]
        # if "fts" in result_list_lower:
        #     ts_bool = True
    return method, basissets  # , ts_bool


def format_freq_matrix(harm_freq, anharm_matrix):
    formated_lines = []
    for freq in harm_freq:
        formated_lines.append(f"{freq}")
    formated_lines.append("lower")
    formated_lines = formated_lines + format_anharm_matrix(anharm_matrix)
    return formated_lines


