#!/usr/bin/env python3
"""Compare this example's ktools result against MultiWell's bundled ch2o+oh reference.

Reads from
  - ours:      ktools_PES_1/kt-canon.canonical   (generated by `make solver`)
  - reference: ch2o+oh/ch2o-oh.canonical.test   (MultiWell's expected output)
and writes ``compare_kt.png`` as a 2x2 grid:
  - top:    forward and reverse k(s) vs the O...H dividing-surface distance for several
            temperatures -- the VTST flux profiles, whose minimum over s (marked *) is the
            variational bottleneck and moves inward as T rises (same location both ways).
  - bottom: forward (dissociation, s^-1) and reverse (capture, cm^3 molecule^-1 s^-1)
            unified canonical k on an Arrhenius axis (k vs 1000/T).

Both decks use the same 11 temperatures and the same 1-reactant / 31-TS / 2-product
topology, so the comparison is point-for-point; they differ only in the molecular data
(ours = CCSD(T)//BHandHLYP, reference = Ali & Barker's published values).
"""

from __future__ import annotations

import math
import os
import sys

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
OURS = os.path.join(HERE, "ktools_PES_1", "kt-canon.canonical")
REF = os.path.join(HERE, "ch2o+oh", "ch2o-oh.canonical.test")
OUT = os.path.join(HERE, "compare_kt.png")

# temperatures to show in the k(s) panels
KS_TEMPS = [100.0, 300.0, 1000.0, 2000.0]


def parse_unified_blocks(path):
    """Return [forward_block, reverse_block]; each block is a list of (T, uk(t))."""
    blocks, cur, in_table = [], None, False
    with open(path, encoding="utf-8", errors="ignore") as fh:
        for line in fh:
            if "unified canonical rate constants" in line:
                cur = []
                blocks.append(cur)
                in_table = False
                continue
            if cur is None:
                continue
            stripped = line.strip()
            if stripped.startswith("#") and "temp" in stripped:
                in_table = True
                continue
            if set(stripped) <= set("- "):  # blank or dashed separator
                if in_table and cur:
                    cur, in_table = None, False
                continue
            if in_table:
                parts = stripped.split()
                try:
                    cur.append((float(parts[1]), float(parts[2])))
                except (IndexError, ValueError):
                    pass
    return blocks


def parse_per_ts_block(path, which):
    """Parse a "...canonical rate constants for all temperatures and transition states"
    block (which=0 forward, 1 reverse): header row ``r  T1  T2 ...`` then one row per
    dividing surface ``r  k(T1)  k(T2) ...``.

    Returns (distances, temps, K) with K[i_dist][j_temp].
    """
    hdr = "reaction canonical rate constants for all temperatures and transition states"
    text = open(path, encoding="utf-8", errors="ignore").read().splitlines()
    starts = [i for i, ln in enumerate(text) if hdr in ln]
    j = starts[which] + 1
    while j < len(text) and not text[j].strip():
        j += 1
    temps = [float(x) for x in text[j].split()[1:]]  # drop the 'r' label
    dists, K = [], []
    j += 1
    while j < len(text):
        parts = text[j].split()
        try:
            r = float(parts[0])
            ks = [float(x) for x in parts[1:]]
        except (IndexError, ValueError):
            break
        if len(ks) != len(temps):
            break
        dists.append(r)
        K.append(ks)
        j += 1
    return dists, temps, K


def geomean_ratio(ours, ref):
    rd = {t: k for t, k in ref}
    rs = [k / rd[t] for t, k in ours if t in rd and rd[t] > 0]
    return math.exp(sum(map(math.log, rs)) / len(rs)) if rs else float("nan")


def _col(temps, T):
    for j, t in enumerate(temps):
        if abs(t - T) < 0.5:
            return j
    return None


def plot_kt(ax, ours, ref, row, title, unit):
    """Unified canonical k on an Arrhenius axis, k vs 1000/T (row 0 forward, 1 reverse)."""
    To, ko = zip(*ours[row])
    Tr, kr = zip(*ref[row])
    ax.semilogy([1000.0 / t for t in Tr], kr, "s--", color="0.4", mfc="white", label="MultiWell reference")
    ax.semilogy([1000.0 / t for t in To], ko, "o-", color="tab:red", label="this example (gausskit)")
    ax.set_title(title)
    ax.set_xlabel("1000 / T   /   K$^{-1}$")
    ax.set_ylabel(unit)
    ax.legend(fontsize=8)
    ax.grid(True, which="both", ls=":", alpha=0.4)
    # secondary top axis labelled in T (K); 1000/T is self-inverse so both maps are 1000/x
    secax = ax.secondary_xaxis("top", functions=(lambda x: 1000.0 / x, lambda x: 1000.0 / x))
    secax.set_xlabel("T / K")
    secax.set_xticks([2000, 1000, 500, 300, 200, 150, 100])


def plot_ks(ax, which, title, unit):
    """k(s) vs O...H dividing-surface distance for several T (which 0 forward, 1 reverse).

    Solid = gausskit, dashed = reference, colour = temperature, * = variational minimum.
    """
    do, to, Ko = parse_per_ts_block(OURS, which)
    dr, tr, Kr = parse_per_ts_block(REF, which)
    cmap = plt.cm.viridis
    n = max(len(KS_TEMPS) - 1, 1)
    for i, T in enumerate(KS_TEMPS):
        c = cmap(i / n)
        jo = _col(to, T)
        if jo is not None:
            ks = [Ko[k][jo] for k in range(len(do))]
            ax.semilogy(do, ks, "o-", color=c, ms=4, label=f"{T:.0f} K (gausskit)")
            kmin = min(range(len(ks)), key=lambda k: ks[k])
            ax.semilogy([do[kmin]], [ks[kmin]], "*", color=c, ms=15, mec="k", zorder=5)
        jr = _col(tr, T)
        if jr is not None:
            ksr = [Kr[k][jr] for k in range(len(dr))]
            ax.semilogy(dr, ksr, "s--", color=c, mfc="white", ms=4, label=f"{T:.0f} K (ref)")
    ax.set_title(title)
    ax.set_xlabel("O···H distance / Å")
    ax.set_ylabel(unit)
    ax.legend(ncol=2, fontsize=7)
    ax.grid(True, which="both", ls=":", alpha=0.4)


def main():
    for p in (OURS, REF):
        if not os.path.exists(p):
            sys.exit(f"missing {p}\nRun `make solver` first to generate our ktools output.")

    ours = parse_unified_blocks(OURS)
    ref = parse_unified_blocks(REF)
    if len(ours) < 2 or len(ref) < 2:
        sys.exit("could not find both unified-canonical blocks in one of the files")

    K_S = "k / s$^{-1}$"
    K_BI = "k / cm$^3$ molecule$^{-1}$ s$^{-1}$"
    fig, ((ax_fks, ax_rks), (ax_fkt, ax_rkt)) = plt.subplots(2, 2, figsize=(12, 9))

    plot_ks(ax_fks, 0, "forward k(s) vs O···H distance   (★ = variational min)", K_S)
    plot_ks(ax_rks, 1, "reverse k(s) vs O···H distance   (★ = variational min)", K_BI)
    plot_kt(ax_fkt, ours, ref, 0, "forward dissociation  PRC → CH₂O + OH", K_S)
    plot_kt(ax_rkt, ours, ref, 1, "reverse capture  CH₂O + OH → PRC", K_BI)

    fig.suptitle("CH₂O + OH entrance: gausskit vs MultiWell ch2o+oh example", fontweight="bold")
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    fig.savefig(OUT, dpi=150)
    print(f"wrote {OUT}")

    # console summary (reverse capture is the physically interesting rate)
    o, r = ours[1], ref[1]
    rd = {t: k for t, k in r}
    print("\nreverse capture  k / cm^3 molecule^-1 s^-1")
    print(f"  {'T/K':>7} {'gausskit':>12} {'reference':>12} {'ratio':>8}")
    for t, k in o:
        if t in rd:
            print(f"  {t:7.0f} {k:12.3e} {rd[t]:12.3e} {k / rd[t]:8.2f}")
    print(f"\n  geomean ratio (capture)      = {geomean_ratio(ours[1], ref[1]):.2f}x")
    print(f"  geomean ratio (dissociation) = {geomean_ratio(ours[0], ref[0]):.2f}x")


if __name__ == "__main__":
    main()
