from operator import index
import numpy as np
import pandas as pd
import os
import re
import sys

_re_freq = re.compile(r"-?[0-9]*\.[0-9]")

def read_anharm_matrix(filename):
    """
    This function takes a gaussian log file with anharmonic analysis
    filename: example.log
    this function return a lower triangular matrix numpy.array
    return anharm_matrix: numpy.array (in cm-1)
    """
    with open(filename) as f:
        found_anharm_matrix = False
        append_bool = False
        anharm_matrix_list = []
        lines = f.readlines()
        for line in lines:
            if "Total Anharmonic X Matrix" in line:
                found_anharm_matrix = True
                append_bool = True
            if found_anharm_matrix == True:
                if "============================================" in line:
                    append_bool = False
                    break

            if append_bool == True:
                line = re.sub(r"D", "E", line)
                anharm_matrix_list.append(line)

    anharm_matrix_list = anharm_matrix_list[2:]
    anharm_matrix_ll = []
    for line in anharm_matrix_list:
        line_split = line.split()
        if line_split != []:
            anharm_matrix_ll.append(line_split)

    anharm_matrix_ll_array = []
    index_line_n_list = []
    max_index = 0
    for n, line in enumerate(anharm_matrix_ll):
        new_line = []
        all_digit = True
        for item in line:
            if item.isdigit():
                new_line.append(int(item))
            else:
                new_line.append(float(item))
                all_digit = False
        if all_digit:
            index_line_n_list.append(n)
            max_index = new_line[-1]

        anharm_matrix_ll_array.append(new_line)

    anharm_matrix = np.zeros((max_index, max_index))

    for n, index_line_n in enumerate(index_line_n_list):
        if n != len(index_line_n_list) - 1:
            next_index_line_n = index_line_n_list[n + 1]
            for line in anharm_matrix_ll_array[index_line_n + 1 : next_index_line_n]:
                i = line[0]
                for _j, item in enumerate(line[1:]):
                    j = anharm_matrix_ll_array[index_line_n][_j]
                    anharm_matrix[i - 1, j - 1] = item
                    # symmetrize anharmonic matrix, modify upper triangular matrix
                    anharm_matrix[j - 1, i - 1] = item
        else:
            for line in anharm_matrix_ll_array[index_line_n + 1 :]:
                i = line[0]
                for _j, item in enumerate(line[1:]):
                    j = anharm_matrix_ll_array[index_line_n][_j]
                    anharm_matrix[i - 1, j - 1] = item
                    # symmetrize anharmonic matrix, modify upper triangular matrix
                    anharm_matrix[j - 1, i - 1] = item

    return anharm_matrix


def format_anharm_matrix(anharm_matrix):
    """
    This function takes a symmetric matrix generated by "read_anharm_matrix"
    anharm_matrix: numpy.array
    return lower triangular matrix list like formated output like (in cm-1):
    1.11111E+1
    1.11111E+1 1.11111E+1
    1.11111E+1 1.11111E+1 1.11111E+1
    """
    _anharm_matrix = np.tril(anharm_matrix)
    format_output = []
    for a in _anharm_matrix:
        format_line = a[a != 0]
        format_line = list(format_line)
        format_output.append(" ".join([f"{i:.5E}" for i in format_line]))
    return format_output


def read_harm_freq(filename):
    """
    This function reads a gaussian log file with anharmonic analysis
    return harmonic frequencies (cm-1)
    """
    with open(filename) as f:
        found_harm_freq = False
        append_bool = False
        harm_freq_list = []
        lines = f.readlines()
        for line in lines:
            if "Fundamental Bands" in line:
                found_harm_freq = True
                append_bool = True
            if found_harm_freq == True:
                if "Overtones" in line:
                    append_bool = False
                    break

            if append_bool == True:
                harm_freq_list.append(line)

    harm_freq_list_clean = []
    for line in harm_freq_list[3:-1]:
        line_split = line.split()
        i = line_split.index("active") + 1

        # in some cases there will be "3722.837**********"
        if "*" in line_split[i]:
            _clean_freq_list = re.findall(_re_freq, line_split[i])
            if _clean_freq_list != []:
                _clean_freq = _clean_freq_list[0]
                line_split[i] = _clean_freq
            else:
                print("Frequency parser failed!")
                print(line_split[i])

        harm_freq_list_clean.append(float(line_split[i]))

    return harm_freq_list_clean

def read_harm_freq_another(filename):
    with open(filename) as f:
        found_harm_freq = False
        append_bool = False
        harm_freq_list = []
        lines = f.readlines()
        for line in lines:
            if "Harmonic frequencies" in line:
                found_harm_freq = True
                append_bool = True
            if found_harm_freq == True:
                if "-------------------" in line:
                    append_bool = False
                    break

            if append_bool == True:
                harm_freq_list.append(line)

    harm_freq_list_clean = []
    for line in harm_freq_list[3:-1]:
        if "Frequencies" in line:
            _freq_list = re.findall(_re_freq, line)
            if _freq_list != []:
                for _freq in _freq_list:
                    harm_freq_list_clean.append(float(_freq))

    return harm_freq_list_clean


def read_method(filename):
    with open(filename) as f:
        lines = f.readlines()
    i_list = []
    j_list = []
    for n, line in enumerate(lines):
        if "1\\1\\" in line:
            i_list.append(n)
        if "@" in line:
            j_list.append(n)

    result_sum = []
    for i, j in zip(i_list, j_list):
        sub_lines = []
        for line in lines[i : j + 1]:
            line = re.sub(r"\n", "", line)
            line = re.sub(r"\ ", "", line)
            sub_lines.append(line)
        result_sum.append("".join(sub_lines))

    # ts_bool = False
    for result_i in result_sum:
        result_list = result_i.split("\\")
        result_list_lower = [item.lower() for item in result_list]
        if "freq" in result_list_lower:
            i = result_list_lower.index("freq")
            method = result_list[i + 1]
            basissets = result_list[i + 2]
        # if "fts" in result_list_lower:
        #     ts_bool = True
    return method, basissets  # , ts_bool


def format_freq_matrix(harm_freq, anharm_matrix):
    formated_lines = []
    for freq in harm_freq:
        formated_lines.append(f"{freq}")
    formated_lines.append("lower")
    formated_lines = formated_lines + format_anharm_matrix(anharm_matrix)
    return formated_lines


def prepare_parsctst(filename_name, harm_freq, anharm_matrix, Egrain_line, barrier=[]):
    
    img_freq = 0
    img_index = None
    ind_array = np.argsort(harm_freq)
    if harm_freq[ind_array][0] < 0:
        if np.any(harm_freq[ind_array][1:] < 0):
            print("More than one imagine freq found!!!")
            print("Please check the calculation!!!")
        else:
            img_index = ind_array[0]
            img_freq = harm_freq[img_index]
    img_nn = anharm_matrix[img_index][img_index]

    # make full anharm matrix (symmetry matrix)
    full_anharm_matrix = (
        anharm_matrix + anharm_matrix.T - np.diag(np.diag(anharm_matrix))
    )
    img_anharm_array = full_anharm_matrix[img_index]
    img_anharm_array = np.delete(img_anharm_array, img_index)

    # remake the harm_freq and anharm_matrix for sctst.dat
    harm_freq = np.delete(harm_freq, img_index)
    full_anharm_matrix = np.delete(full_anharm_matrix, img_index, axis=0)
    full_anharm_matrix = np.delete(full_anharm_matrix, img_index, axis=1)
    anharm_matrix = np.tril(full_anharm_matrix)

    # prepare inputfile
    input_list = []
    input_list.append(filename_name)
    input_list.append(f"At ??/?? level of theory")
    input_list.append(f"Anharmonicity from ??/?? level")
    input_list.append(" ")

    input_list.append(f'{len(harm_freq)}, {0}, {0}, "We" ')
    input_list.append(" ")
    formated_lines = format_freq_matrix(harm_freq, anharm_matrix)
    input_list = input_list + formated_lines
    input_list.append(" ")
    input_list.append("0    'AMUA'")
    input_list.append(f"{Egrain_line}")
    input_list.append(f"'nochekstart'  {filename_name}.chk")
    input_list.append("VPT4A")
    if len(barrier) == 0:
        barrier_text = "<forward_barrier>  <backword_barrier>"
    else:
        barrier_text = f"{barrier[0]:.4f}  {barrier[1]:.4f}"
    input_list.append(f'{barrier_text}  "kcal"')
    input_list.append(f"{img_freq}  {img_nn:.5E}")
    input_list = input_list + [f"{item:.5E}" for item in img_anharm_array]
    input_list.append(" ")
    pardata = [
        "1       !nwalkers",
        "70.d0   !perc_wind_overlap",
        "0.60d0  !flatness",
        "1       !Writing enable (1) or disable (2)",
        "0       !Seed modifier",
        "cost    !Windows balance  (cost / low / high)",
    ]
    input_list += pardata
    input_list.append(" ")

    return input_list

def prepare_bdens(filename_name, harm_freq, anharm_matrix, Egrain_line):
    input_list = []
    input_list.append(filename_name)
    input_list.append(f"At ??/?? level of theory")
    input_list.append(f"Anharmonicity from ??/?? level")
    input_list.append(" ")
    
    input_list.append(f'{len(harm_freq)}, {0}, {0}, "We" ')
    input_list.append(" ")
    formated_lines = format_freq_matrix(harm_freq, anharm_matrix)
    input_list = input_list + formated_lines
    input_list.append(" ")
    input_list.append("0    'AMUA'")
    input_list.append(" ")
    input_list.append(f'{Egrain_line}   "good"  "auto"   450000. ')
    input_list.append(f"'nochekstart'  {filename_name}.chk")
    input_list.append(" ")
    return input_list

def main(filename):
    # default Egrain_line
    Egrain_line = "10	3000	4000	50000"
    # filename = "TS2.log"
    filename_name = filename.split(".")[0]

    harm_freq = read_harm_freq(filename)
    if len(harm_freq) == 0:
        harm_freq = read_harm_freq_another(filename)
    if len(harm_freq) == 0:
        print(f"no frequancy data found in {filename}!!")

    harm_freq = np.array(harm_freq)
    anharm_matrix = read_anharm_matrix(filename)

    # check if calculation type is TS
    ts_bool = False
    ind_array = np.argsort(harm_freq)
    if harm_freq[ind_array][0] < 0:
        ts_bool = True

    if ts_bool:  # prepare parsctst.dat
        print(f"Found imagine frequency {harm_freq[ind_array][0]} cm-1, generateing parsctst.dat")
        output = f"{filename_name}.parsctst.dat"
        input_list = prepare_parsctst(filename_name, harm_freq, anharm_matrix, Egrain_line)

        print(f"<forward_barrier>  <backword_barrier> need specify in {output}")

    else:  # prepare bdens.dat
        output = f"{filename_name}.bdens.dat"
        print(f"Found No imagine frequencies, generateing {output}")
        input_list = prepare_bdens(filename_name, harm_freq, anharm_matrix, Egrain_line)


    with open(output, "w") as f:
        f.writelines([line + "\n" for line in input_list])
    with open(".".join(output.split(".")[1:]), "w") as f:
        f.writelines([line + "\n" for line in input_list])


if __name__ == "__main__":

    filename = sys.argv[1]
    main(filename)
